oil:
  postgres:
    host: 192.168.23.205
    port: 15432
    user: postgres
    password: jinzewei
    schema: loader
  clickhouse:
    host: 192.168.23.205
    port: 8123
    user: public
    password: nvr2022
    database: oildb
  redis:
    host: 192.168.23.205
    port: 6379
    password: 123456
    database: 2
  algorithm:
    host: 192.168.23.205
    port: 5000
  log:
    level: info